#ifndef CONFIG_H
#define CONFIG_H

#define POINTS_N (1 << 12)
#define RUN_TIME_MS 2000
#define POLLING_MODE 0
#define DMA_MODE_ADC_MULTI_CHANNEL 0
#define DMA_MODE_DMA_MULTI_CHANNEL 0
#define DMA_MODE_DONE_THE_PROPER_WAY 1

#endif // CONFIG_H